/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    maven {
        url = uri("https://frcmaven.wpi.edu/artifactory/release")
    }
    mavenCentral()
}


dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // Kaitai Struct runtime for Java
    implementation("io.kaitai:kaitai-struct-runtime:0.10")

    // Jackson dependencies
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.19.2")
    implementation("com.fasterxml.jackson.core:jackson-core:2.19.2")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.19.2")

    // Quickbuf runtime
    implementation("us.hebi.quickbuf:quickbuf-runtime:1.4")

    // NT4 client + struct types
    implementation("edu.wpi.first.ntcore:ntcore-java:2025.1.1")

    // DataLog reader + struct unpacking helpers
    implementation("edu.wpi.first.wpilibj:wpilibj-java:2025.1.1")
    implementation("edu.wpi.first.wpiutil:wpiutil-java:2025.1.1")
    implementation("edu.wpi.first.wpimath:wpimath-java:2025.1.1")

    // xchart for plotting
    implementation("org.knowm.xchart:xchart:3.8.6")
}

java { 
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    // Define the main class for the application.
    mainClass = "org.heatmapvis.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
