/*
 * This source file was generated by the Gradle 'init' task
 */
package org.heatmapvis;

import org.heatmapvis.ui.Windows;

public class App {
    public static void main(String[] args) {
        new Windows();
    }
}
